name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-13
          - ubuntu-24.04-arm
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install & build
        env:
          IS_EVEN_DEBUG: 1
          IS_EVEN_LIGHT: 1
        run: npm install

      - name: Run tests
        env:
          IS_EVEN_DEBUG: 1
          IS_EVEN_LIGHT: 1
        run: npm test
