name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install & build
        env:
          IS_EVEN_DEBUG: 1
          IS_EVEN_LIGHT: 1
        run: npm install

      - name: Run tests
        env:
          IS_EVEN_DEBUG: 1
          IS_EVEN_LIGHT: 1
        run: npm test

  test_macos_intel:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install & build
        env:
          IS_EVEN_DEBUG: 1
          IS_EVEN_LIGHT: 1
        run: npm install

      - name: Run tests
        env:
          IS_EVEN_DEBUG: 1
          IS_EVEN_LIGHT: 1
        run: npm test

  test_macos_arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install & build
        env:
          IS_EVEN_DEBUG: 1
          IS_EVEN_LIGHT: 1
        run: npm install

      - name: Run tests
        env:
          IS_EVEN_DEBUG: 1
          IS_EVEN_LIGHT: 1
        run: npm test
